Aded tests for book and category
nshtykh/online-book-store pull request #13
Opened 2024-01-09 18:47 UTC by nshtykh

I will add more tests with time.

2024-01-10 09:01 UTC, MinoDentori approved these changes
Looks good to me

2024-01-10 09:35 UTC, yevheniisynytsia requested changes
Great job! 
Left some minor comments to update tests' quality

2024-01-10 09:35 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/controller/BookControllerTest.java
> +        expected.setTitle(requestDto.getTitle());
this is ok, but using `@Accessors(chain = true)` is more convenient

2024-01-10 09:35 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/controller/CategoryControllerTest.java
> +    @WithMockUser(username = "admin", roles = {"ADMIN"})
I would better test with user role so that we are sure user role is configured properly

2024-01-10 09:35 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/controller/CategoryControllerTest.java
> +                CategoryResponseDto[].class);
you can map into list 
`List<CategoryResponseDto> actual = objectMapper.readValue(result.getResponse()
                .getContentAsString(), new TypeReference<List<CategoryResponseDto>>() {});` (not sure if TypeReference is required, you can test it)

2024-01-10 09:35 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/repository/BookRepositoryTest.java
> +        Assertions.assertEquals(1, actualBook.getCategories().size());
let's create an expected book so that we are testing all the fields

2024-01-10 09:35 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/service/book/BookServiceImplTest.java
> +    private BookServiceImpl bookService;
place `InjectMocks` under mocks

2024-01-10 09:35 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/service/book/BookServiceImplTest.java
> +        assertEquals(expected.size(), actual.size());
you can just compare lists using equals, can't you?

2024-01-10 09:35 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/service/category/CategoryServiceImplTest.java
> +    private CategoryServiceImpl categoryService;
place under mocks

2024-01-10 09:35 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/service/category/CategoryServiceImplTest.java
> +        assertEquals(expected.size(), actual.size());
compare lists if possible

2024-01-11 07:55 UTC, d1sam requested changes
good job, but please use what about `assertIterableEquals` for iterable objects.

2024-01-11 07:55 UTC, d1sam commented on src/test/java/com/example/onlinebookstore/controller/CategoryControllerTest.java
> +        Assertions.assertEquals(expected, actual);
what about [assertIterableEquals](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/Assertions.html#assertIterableEquals-java.lang.Iterable-java.lang.Iterable-)([Iterable](https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html?is-external=true)<?> expected, [Iterable](https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html?is-external=true)<?> actual)

2024-01-11 07:55 UTC, d1sam commented on src/test/java/com/example/onlinebookstore/service/book/BookServiceImplTest.java
> +        assertEquals(expected, actual);
what about [assertIterableEquals](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/Assertions.html#assertIterableEquals-java.lang.Iterable-java.lang.Iterable-)([Iterable](https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html?is-external=true)<?> expected, [Iterable](https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html?is-external=true)<?> actual)

2024-01-18 09:00 UTC, d1sam approved these changes
well done!

2024-01-30 19:28 UTC, merged