implemented JWT support
nshtykh/online-book-store pull request #8
Opened 2023-12-26 13:25 UTC by nshtykh

2023-12-26 14:11 UTC, andrii-hoienko requested changes

2023-12-26 14:11 UTC, andrii-hoienko commented on pom.xml
> +            <version>0.11.5</version>
Please use variables to define versions

2023-12-26 14:11 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/security/CustomUserDetailsService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("Can't find user by email"));
Specify the input email in the error message

2023-12-26 14:11 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
Please don`t forget about constants

2023-12-26 14:11 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
magic number

2023-12-26 14:11 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Please make "Bearer " constant

2023-12-26 14:11 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/03-create-roles-table.yaml
> +
Please add empty line in the end of file

2023-12-27 15:52 UTC, vovasalyha requested changes
Please change the base branch for this PR, because there are changes from previous one.

2023-12-28 10:45 UTC, bhdnchui approved these changes
Good job!

2023-12-29 12:18 UTC, merged